// build_docs.js -- Generate EN Word + CN Word for bioRxiv submission
const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, PageNumber } = require("docx");

const NODE_PATH = "C:/Users/wkr20/.workbuddy/binaries/node/workspace/node_modules";
// Ensure docx is resolvable
let docx;
try { docx = require("docx"); } catch(e) { docx = require(NODE_PATH + "/docx"); }

const Q = String.fromCharCode; // no unicode bullets
const DXA = (inch) => Math.round(inch * 1440);
const A4_W = 11906, A4_H = 16838;
const MARGIN = DXA(1.0);
const CONTENT_W = A4_W - 2 * MARGIN;

function hr(width) {
  return new Paragraph({ spacing: { after: 80 }, border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "CCCCCC", space: 1 } } });
}

function h1(text) { return new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 240, after: 120 }, children: [new TextRun({ text, bold: true, size: 32 })] }); }
function h2(text) { return new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 100 }, children: [new TextRun({ text, bold: true, size: 28 })] }); }
function h3(text) { return new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 160, after: 80 }, children: [new TextRun({ text, bold: true, size: 26 })] }); }
function p(text)  { return new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text, size: 22 })] }); }
function pi(text) { return new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text, italics: true, size: 22 })] }); }
function pb(text) { return new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text, bold: true, size: 22 })] }); }
function pc(text) { return new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 40 }, children: [new TextRun({ text, size: 22 })] }); }

function tbl(headers, rows) {
  const border = { style: BorderStyle.SINGLE, size: 1, color: "999999" };
  const bd = { top: border, bottom: border, left: border, right: border };
  const n = headers.length;
  const colW = Math.floor(CONTENT_W / n);
  const cols = Array(n).fill(colW);
  const hdrRow = new TableRow({ children: headers.map(h => new TableCell({
    borders: bd, width: { size: colW, type: WidthType.DXA },
    shading: { fill: "E8E8E8", type: ShadingType.CLEAR },
    margins: { top: 60, bottom: 60, left: 100, right: 100 },
    children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 20 })] })]
  }))});
  const dataRows = rows.map(row => new TableRow({ children: row.map(cell => {
    const segs = String(cell).split("\n");
    const paras = segs.map(s => new Paragraph({ children: [new TextRun({ text: s, size: 20 })], spacing: { after: 0 } }));
    return new TableCell({ borders: bd, width: { size: colW, type: WidthType.DXA }, margins: { top: 50, bottom: 50, left: 100, right: 100 }, children: paras });
  })}));
  return new Table({ width: { size: CONTENT_W, type: WidthType.DXA }, columnWidths: cols, rows: [hdrRow, ...dataRows] });
}

const foot = new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Page ", size: 18 }), new TextRun({ children: [PageNumber.CURRENT], size: 18 })] })] });

// ==================== ENGLISH ====================
const enChildren = [
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 4 }, children: [new TextRun({ text: "Reimplementing and Scaling UniPert-G2CP:", bold: true, size: 34 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 4 }, children: [new TextRun({ text: "A 162-Cell-Line Genome-Wide Platform for Perturbation-to-Phenotype Prediction", bold: true, size: 30 })] }),
  pc(""),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "Kairui Wei\u00B9*, Lijing Zhan\u00B9, Canyang Qi\u00B9", bold: true, size: 26 })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "\u00B9Xinjiang Medical University, Urumqi 830011, China", size: 22 })] }),
  pc(""),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "*Correspondence: 2742391737@qq.com", size: 20, color: "666666" })] }),
  hr(CONTENT_W),
  h2("Abstract"),
  p("UniPert-G2CP (Li et al., Cell, 2026) introduced a unified framework for predicting transcriptomic responses to genetic and chemical perturbations across five cancer cell lines. To date, no independent reimplementation or large-scale extension has been reported."),
  p("We built a simplified variant of the UniPert-G2CP architecture, integrating Extended-Connectivity Fingerprints 4 (ECFP4) compound fingerprints, static ESM2-8M gene embeddings (substituting for the original MSA+GNN protein encoder) as anchors for Compound-Protein Interaction (CPI) alignment, NT-Xent contrastive learning, and two-stage transfer, and scaled it to substantially expanded compound and cell-line coverage (32,039 compounds across 162 cell lines) with genome-wide output (12,328 genes)."),
  p("Held-out genetic perturbation PCC = 0.442; novel drug PCC = 0.3047; directional accuracy for top-5% effect-size genes = 73.8%. CPI enrichment factor at top 0.5% reached 139 on the Touchstone set, though this metric reflects training-set ranking consistency rather than out-of-distribution generalization due to overlap with training CPI pairs. Benchmark-consistent evaluation: mechanism-clustering standardized mean difference (SMD) = 1.636; self-consistency Mantel \u03c1 = 0.852 (under our evaluation setup); Tanimoto SMD validation = 1.613. Of four literature-supported perturbation-gene pairs queried, two were recapitulated in the model output (dexamethasone \u2192 TSC22D3/NFKBIA/FKBP5 upregulation in HA1E; bortezomib \u2192 BAG3/DNAJB1/HSPA1A upregulation in HA1E), one was absent (CD36 depletion \u2192 PPARG/CEBPA in ASC), and one was partially recapitulated (metformin \u2192 SLC7A5 downregulation predicted in HEPG2, while PLIN2 was absent)."),
  p("The architecture scales to increased cell-line and compound diversity but performance falls short of the original study in two respects: mechanism-clustering SMD below the original\u2019s value (1.636 vs. 1.85; a reference comparison given differing training configurations), possibly linked to CPI vocabulary mismatch, and limited per-gene directional prediction fidelity partially due to incomplete pathway coverage and cell-type distribution shift. All results are computational hypotheses and have not been experimentally validated. These findings provide the first independent benchmark of UniPert-G2CP at expanded scale, revealing intrinsic bottlenecks for genome-wide virtual-cell prediction."),
  p(""),
  pb("Keywords: "),
  p("perturbation prediction, transcriptomics, contrastive learning, drug response, CRISPR screening, transcriptomic perturbation"),
  hr(CONTENT_W),
  h2("1. Introduction"),
  p("Predicting transcriptomic responses to molecular perturbations has emerged as a central challenge in AI-driven biology. Several approaches have been proposed: scGen [10] uses variational autoencoders for single-cell perturbation response; CPA [11] uses an autoencoder framework for combinatorial perturbation prediction; ChemPert [12] predicts drug-induced transcriptomic changes via a multi-task model; and GEARS [6] introduced a graph-based framework integrating gene co-expression. UniPert-G2CP (Li et al., Cell, 2026) [1] unified genetic and chemical perturbation prediction in a single contrastive-embedding space across five cancer cell lines. To date, no independent reimplementation or large-scale extension of UniPert-G2CP has been reported."),
  p("This work is motivated by the need to independently verify the reproducibility and scalability of the reported architecture. The original study released code and reproducibility resources [2,3]; we did not directly use them, but instead reconstructed the architecture from the paper description to test whether key design components transfer at larger scale."),
  p("This work contributes: (1) an independent full-scale reconstruction of the architecture at substantially expanded compound and cell-line coverage (32,039 compounds, 162 cell lines, genome-wide output); (2) a disentangled evaluation framework that distinguishes held-out prediction, self-consistency, and benchmark-consistent metrics; (3) a transparent assessment of per-gene prediction fidelity on literature-supported cases. This work is an independent reimplementation and extension of the UniPert-G2CP framework [1] and is not affiliated with the original authors. All comparisons to original results are based on publicly released evaluation datasets [3]."),
  h2("2. Methods"),
  h3("2.1 Datasets and Preprocessing"),
  p("We utilized LINCS L1000 (level 5, GSE92742; moderated Z-scores, 305,297 samples), DepMap CRISPR screens (23Q2 release, CERES gene-effect scores, 1,095 cell lines \u00d7 17,931 genes), and Perturbation Consensus Ligands (PCL) annotations linking BRD compound IDs (the LINCS platform\u2019s compound identifiers) to therapeutic mechanism-of-action (MoA) labels. We retained 143 cell lines with LINCS level-5 training samples as the training domain and added 19 GEO (Gene Expression Omnibus)-derived cell lines (HUVEC, PBMC immune subsets, and other primary/vascular/pancreatic lines; not included in model training, used exclusively for out-of-domain evaluation) from 12 GEO perturbation datasets (GSE11917, GSE17579, GSE20986, GSE21413, GSE25941, GSE33622, GSE50378, GSE50397, GSE53751, GSE62914, GSE22886, GSE60235), forming a 162-cell-line vocabulary. ASC is a LINCS training-domain cell line (with additional GEO data from GSE61302); the CD36 knockout \u00d7 ASC query in Section 3.5 is a zero-shot prediction because this line lacks gene-perturbation training samples. Probe-level expression was mapped to gene symbols and z-score normalized per sample (aligned to the LINCS level-5 distribution) before merging. The full compound set comprises 32,039 BRD compounds with LINCS level-5 signatures; their ECFP4 fingerprints (2048-bit, radius 2) were generated via RDKit Morgan fingerprints."),
  h3("2.2 Model Architecture"),
  p("The architecture follows UniPert-G2CP: drug encoder (ECFP4, 2048-bit \u2192 512-dim Linear); gene encoder (4,994\u00d7512 embedding table, first 320 dims initialized from ESM2-8M vectors, with the remaining 192 dims left at the Embedding layer’s default random initialization; the embedding table is frozen during Stage B finetuning); contrastive learning with NT-Xent (\u03c4=0.07) and CPI alignment (Section 2.3); phenotype head (LayerNorm(544) \u2192 Linear(544\u21921024) \u2192 GELU \u2192 Linear(1024\u219212,328), no dropout layer); cell embedding (162\u00d732, learnable). Crucially, the gene embedding table is frozen during Stage B finetuning; ESM2 vectors serve as fixed reference targets for CPI alignment rather than as trainable representations of protein structure. The 4,994 perturbable genes constitute the perturbation vocabulary; the 12,328-gene output is the prediction vocabulary (highly variable genes from the DepMap\u2013LINCS intersection)."),
  h3("2.3 Training Protocol"),
  p("Training proceeds in two stages. Stage A (DepMap pretraining): a gene-essentiality network is pretrained on CERES gene-effect scores (gene embeddings initialized from ESM2-8M vectors), providing semantic gene initialization. Stage B (LINCS finetuning): the main model is trained on LINCS level-5 moderated Z-scores in frozen mode\u2014the gene encoder, phenotype head, and cell embedding are frozen, and only the drug encoder (ECFP4 projection) is finetuned\u2014a frozen design that keeps the gene-side parameters bit-identical, thereby preserving genetic-perturbation prediction metrics during chemical finetuning\u2014using AdamW (learning rate 3\u00d710\u207B\u2074, weight decay 1\u00d710\u207B\u2074, 40 epochs, cosine-annealing schedule, gradient accumulation factor 4), initialized from the preceding LINCS-trained checkpoint via partial state-dict transfer. The total loss combines phenotype regression (MSE plus 1\u2212PCC, weight 1.0), NT-Xent contrastive learning (\u03c4=0.07, weight 1.0; negatives are in-batch random samples), CPI alignment (weight 0.8; positive pairs are drug\u2013gene pairs sharing at least one ChEMBL (release 37) therapeutic target, 19,161 pairs, of which up to 128 were dynamically sampled per batch; for each positive pair one negative gene was drawn uniformly at random from the gene vocabulary, without excluding potential targets), a structural-similarity enhancement loss (weight 0.3; within each batch, drug pairs with Tanimoto fingerprint similarity >0.3 were pulled together weighted by similarity), and ESM anchoring (weight 0.05; an MSE loss pulling the first 320 dimensions of the gene embeddings toward precomputed ESM2-8M vectors). In Stage A, DepMap CERES gene-effect scores are used directly as regression targets (missing values masked); in Stage B, LINCS moderated Z-scores are the regression targets. Both modalities share the same phenotype head in Stage B. The cell embedding is a learnable 32-dim table (initialized N(0,1)) and is frozen during Stage B; Stage A trains a separate DepMap essentiality network with its own cell embedding for 1,095 DepMap lines, which is not the 162-line LINCS cell table used in Stage B. ESM2-8M vectors are computed once during preprocessing (Section 4.2) and frozen thereafter."),
  p("All quantitative metrics reported in Sections 3.1\u20133.4 were obtained from a single model trained with the configuration described above (g2cp_full_cpi_v7.pt); no post-hoc hyperparameter tuning was performed after evaluation. The case queries in Section 3.5 were performed through the interactive API platform."),
  h2("3. Results"),
  h3("3.1 Held-Out Perturbation Prediction"),
  p("Metrics. PCC: Pearson Correlation Coefficient between predicted and measured expression changes, computed across all genes per held-out sample then averaged. Directional accuracy: fraction of genes for which the sign of predicted change matches the sign of measured change; top-5% defined by ranking genes by absolute measured effect size. SMD: Standardized Mean Difference, calculated as (mean intra-class cosine similarity \u2212 mean overall cosine similarity) / pooled standard deviation, grouping drugs by Mechanism of Action. Mantel self-consistency \u03c1: per-PCL Spearman correlation between molecular embedding similarity and model-predicted effect similarity, averaged across cell lines (evaluation script in the repository)."),
  pb("Table 1. Held-out perturbation prediction performance. Perturbations (drug or gene identity) were randomly split, with 10% assigned to the test set; all samples of a held-out perturbation, across doses and cell lines, were excluded from training. Genetic perturbation PCC: perturbation-level held-out evaluation (10% of perturbations held out), computed on genetic-perturbation samples across 162 cell lines on the 978-gene subset with DepMap CERES ground truth (the 978 LINCS L1000 landmark genes covered by the platform's measurement probes; knockout samples have measured values only for these genes). Novel drug PCC: perturbation-level held-out evaluation (10% of perturbations held out), computed on chemical-perturbation samples on the full 12,328-gene output. Directional accuracy: top 5% effect-size genes in the held-out set."),
  tbl(["Metric","Value","Context"],
    [["Genetic perturbation PCC","0.442","10% perturbations held out"],
     ["Novel drug PCC","0.3047","Not reported in original"],
     ["Directional accuracy (genome-wide)","60.8%","compared to random baseline 50%"],
     ["Directional accuracy (top-5%)","73.8%","random baseline 50%"]]),
  h3("3.2 Compound-Protein Interaction Enrichment"),
  pb("Table 2. CPI enrichment factor at top percentiles (random baseline = 1). These values reflect ranking consistency within the training-derived annotation space rather than out-of-distribution generalization (see Section 4.1)."),
  tbl(["Percentile","This study"],
    [["Top 0.5%","139"],["Top 1%","77"]]),
  h3("3.3 Benchmark-Consistent Evaluation"),
  pb("Table 3. Benchmark-consistent metrics on the original evaluation datasets. Evaluation set notes clarify differences in data scope."),
  tbl(["Metric","This study"],
    [["SMD (cosine)","1.636"],["ECFP4 Tanimoto SMD","1.613"],["Mantel self-consistency \u03c1","0.852"],["Cell lines","162"]]),
  p("Notes: SMD was computed on the MoA evaluation table (ChEMBL therapeutics) released in the original study\u2019s Zenodo archive [3] with the same per-class filtering criterion (>25 drugs per MoA class) as the original; because the training configuration (CPI pairs, protein encoder) differs from the original, the SMD value is presented as a reference comparison (1.636 vs. 1.85) rather than a strict reproduction gap. Mantel \u03c1 was computed with a script implementing the original definition (per-PCL Spearman correlation between molecular embedding similarity and model-predicted effect similarity) using Subramanian PCL [5] mechanism annotations; because the PCL filtering and cell-line selection differ from the original, the Mantel \u03c1 values are not directly comparable (0.852 vs. 0.43, reported for reference only)."),
  h3("3.4 Per-Cell-Line Drug Perturbation Resolution"),
  p("We evaluate single-cell-line resolution within our training domain by computing held-out drug perturbation PCC separately for each cell line (120 lines with sufficient samples). The mean per-cell-line PCC is 0.359 (median 0.362, range -0.004 to 0.615; A549 = 0.362, MCF7 = 0.360). Stratifying by cell type, cancer lines (n = 78) achieved a lower mean PCC of 0.296 (median 0.324), whereas normal/primary lines (n = 37) reached 0.480 (median 0.502) and stem/neural/adipose lines (n = 5) 0.446, indicating that prediction is more challenging for the heterogeneous cancer lines. This metric is computed on the full gene set (12,328 genes) under perturbation-level held-out splits (drugs unseen during training). The original reports PCC = 0.92\u20130.98 on sciPlex3 [1], but those values were obtained under near-domain splits (known compounds at novel doses/cell lines) on a top-DEG subset; our lower per-cell-line values reflect the more stringent setting of full-gene, unseen-perturbation evaluation on the larger and more heterogeneous LINCS screening library."),
  h3("3.5 In Silico Case Query on Literature-Supported Pairs"),
  p("All predictions are computational hypotheses and have not been experimentally verified. These cases serve only as illustrative examples of model behavior, not as evidence of therapeutic efficacy. The four cases were selected based on literature availability only and were not used to tune any model hyperparameter. They were selected as well-characterized, experimentally validated perturbation-gene pairs spanning glucocorticoid, proteotoxic stress, adipogenic, and metabolic pathways; they were chosen for their literature support rather than for positive model performance. Three cell lines are involved: HA1E (two cases) and HEPG2 are within the core training set; ASC is also within the training-domain vocabulary but lacks gene-perturbation training samples, so the CD36 knockout \u2192 ASC query represents a zero-shot prediction scenario. To assess whether the model recapitulates known perturbation-gene relationships, we queried four literature-supported pairs with matching perturbation-cell line combinations (Table 4). Of the four, two were recapitulated in the model output. Dexamethasone treatment of HA1E upregulates TSC22D3 (GILZ), NFKBIA (I\u03baB\u03b1), FKBP5, and CEBPD\u2014canonical glucocorticoid receptor targets [8]. Bortezomib (a proteasome inhibitor) treatment of HA1E upregulates BAG3, DNAJB1, and HSPA1A\u2014heat-shock response genes whose induction by proteasome inhibition is a well-established mechanism [13]. However, one pair\u2014CD36 depletion \u2192 PPARG/CEBPA downregulation in ASC\u2014was absent from the predicted differentially expressed genes. The predicted HLA-A/HLA-C upregulation in ASC, rather than the expected adipogenic markers, may reflect batch effects or cell-state-related signals in the LINCS training data for this line, highlighting the challenge of disentangling perturbation-specific effects from experimental confounding. For metformin in HEPG2, SLC7A5 downregulation was predicted (rank 6 among downregulated genes, consistent with the literature direction [9]), while PLIN2 was absent. When absent, Table 4 reports the model\u2019s actual top predictions instead. We computationally assessed specificity by confirming that none of the marker genes (TSC22D3, FKBP5, BAG3, DNAJB1, HSPA1A) was among the top-10 predicted up-regulated genes for any of seven other drugs (vorinostat, tamoxifen, metformin, cisplatin, imatinib, erlotinib, sorafenib) in the same HA1E cell line; BAG3 appeared in erlotinib\u2019s top-10 down-regulated genes (rank 8), in the opposite direction to bortezomib."),
  pb("Table 4. In silico case-query results on literature-supported pairs. Raw predictions shown; recapitulated cases verified for drug specificity (the marker gene is not predicted by other drugs in the same cell line)."),
  tbl(["Perturbation","Predicted genes","Model match"],
    [["CD36 perturb. x ASC","Model: HLA-A\u2191, HLA-C\u2191, GAPDH\u2191, RAC2\u2191; Lit: PPARG\u2193, CEBPA\u2193 [7]","Not recapitulated; model predicts other genes"],["Dexamethasone x HA1E","TSC22D3\u2191, NFKBIA\u2191, FKBP5\u2191, CEBPD\u2191","Recapitulated [8]"],["Bortezomib x HA1E","BAG3\u2191, DNAJB1\u2191, HSPA1A\u2191, HMOX1\u2191","Recapitulated [13]"],["Metformin x HEPG2","Model: SLC7A5\u2193 (rank 6), UBC\u2191 (rank 9) Lit: SLC7A5\u2193, PLIN2\u2193 [9]","Partially recapitulated: SLC7A5\u2193 predicted; PLIN2 absent"]]),
  p("Overall, two of the four cases were fully recapitulated, one was absent, and one was partially recovered. These results represent an initial set of four cases and should not be interpreted as a systematic assessment. Larger-scale validation is needed before generalizing about per-gene directional prediction fidelity. The absent literature-supported relationship (CD36 \u2192 PPARG/CEBPA) and the partially recovered metformin case (SLC7A5\u2193 predicted, PLIN2 absent) highlight the gap between genome-wide accuracy (PCC = 0.442) and per-gene reliability (60.8% directional accuracy), and reflect limited pathway representation in LINCS training data plus cell-type distribution shift for held-out lines."),
  h2("4. Discussion"),
  h3("4.1 Contributions"),
  p("This study makes three contributions. First, it independently builds the UniPert-G2CP architecture at substantially expanded compound and cell-line coverage (32,039 compounds across 162 cell lines, genome-wide output), demonstrating that the architecture is reproducible and extensible beyond the original five-line setting. Second, it disentangles the boundary between held-out generalization metrics and self-consistency indicators in the original evaluation framework, clarifying the interpretation context for each metric class. Third, it provides qualitative case demonstrations on literature-supported perturbation–gene pairs across multiple pathways, transparently reporting both positive and negative results."),
  p("Held-out perturbation metrics (genetic perturbation PCC = 0.442; novel drug PCC = 0.3047; directional accuracy = 73.8% on top-5% effect-size genes) are reported as standalone reference values. CPI enrichment (EF = 139 at top 0.5%) was computed on the Touchstone CPI evaluation set (the LINCS mechanism-annotated compound\u2013target validation set; 797 compounds \u00d7 225 targets; an approximation, not a strict hold-out); because 54.9% of its positive pairs overlap with our ChEMBL-derived training CPI pairs (the EF drops to 109 after removing overlapping pairs), this metric primarily reflects ranking consistency within the training-derived annotation space rather than out-of-distribution generalization; we report it here for reference only. The self-consistency Mantel \u03c1 (0.852) was computed on Subramanian PCL [5] mechanism annotations (filtered to \u22653 drugs per class: 48 classes, 366 compounds). Values obtained on different PCL sets should not be directly compared. All metrics should be interpreted within their respective evaluation contexts."),
  h3("4.2 Rationale for Static Protein Embedding Anchoring"),
  p("For each of the 4,994 perturbable genes, the protein sequence was taken from the human reviewed (Swiss-Prot) UniProt proteome (reviewed:true, organism:9606), matched by gene symbol from the FASTA header (GN= field); 12 genes without a matched protein sequence were assigned zero vectors. ESM2-8M [4] encoding was performed once during preprocessing on an NVIDIA RTX 3050 Ti GPU (4 GB VRAM): per-residue representations from the top layer were mean-pooled to 320-dim vectors, which anchor the first 320 dimensions of the 512-dim gene embedding table. The gene embedding table is frozen during Stage B finetuning and subsequent training. Our simplified design deliberately isolates the effect of CPI alignment on the compound embedding space through a static protein prior, but as a consequence protein structural information is not integrated into the prediction pathway. This constitutes a key simplification relative to the original trainable protein GNN, and may contribute to the observed SMD gap. Incorporating MSA and trainable GNN encoding is a direction for future work."),
  h3("4.3 SMD Gap Analysis"),
  p("Because SMD was computed on the same MoA evaluation table with the same per-class filtering criterion (>25 drugs per MoA class) as the original study (Table 3 notes), we present the comparison as a reference; differences in training configuration (CPI pairs, protein encoder) preclude a strict reproduction comparison: the mechanism-clustering SMD of the learned embedding is 1.636, exceeding the ECFP4 Tanimoto fingerprint baseline (1.613) but remaining below the original study\u2019s 1.85 (88.5% attainment). We hypothesize two factors for the remaining gap: (1) CPI vocabulary mismatch: the CPI training pairs used here are based on ChEMBL annotations for the LINCS BRD compound vocabulary (19,161 unique pairs); these differ substantially from the compound\u2013target pairs used in the original study, and may map some structurally dissimilar compounds to similar vectors based on noisy target annotations. (2) Objective conflict: minimizing transcriptional MSE may separate compounds with different effects even if they share a mechanism. Alternative explanations (the simplified protein encoder, frozen gene encoder limiting contrastive learning, hyperparameter sensitivity, data-distribution differences) remain plausible and should be systematically tested in future ablation studies."),
  h3("4.4 Limitations"),
  p("(1) Single-gene direction prediction remains noisy (60.8% genome-wide); the platform is a candidate-screening and hypothesis-generation tool, not a substitute for experimental validation. (2) The protein encoder is simplified relative to the original. (3) CPI training data has reached its physical ceiling under the current compound vocabulary. (4) The SMD evaluation dataset reflects properties of well-characterized therapeutics and is not representative of screening-library compounds. (5) The original study released code and pretrained models [2,3]; our independent implementation was built from the paper description and did not directly use their released training pipeline, so implementation differences may remain. (6) The increased cell-line coverage introduces greater biological heterogeneity, which itself can lower aggregate performance metrics; genome-wide output (12,328 genes) is more challenging than the original landmark-gene prediction. The 192 randomly initialized and frozen dimensions in the gene embedding table may contribute to suboptimal gene representation; these dimensions were inherited from an earlier 512-dim architecture and retained for checkpoint compatibility, and we did not ablate this design choice. Future work could explore full-dimensional ESM2 initialization or trainable gene embeddings. Future work includes: ablation studies to isolate the contribution of each architectural component; incorporating the original MSA and protein-similarity GNN pipeline; extending to single-cell resolution; and building domain-specific CPI annotation datasets that match the compound vocabulary."),
  h2("5. Conclusion"),
  p("We have independently built and evaluated the UniPert-G2CP architecture at increased cell-line and compound diversity (162 cell lines, 32,039 compounds, genome-wide output). The architecture recapitulates key properties of the original design but shows mechanism-clustering SMD below the original\u2019s value (1.636 vs. 1.85) and limited per-gene directional prediction fidelity\u2014whose root causes (CPI vocabulary mismatch vs. objective conflict vs. hyperparameter tuning) remain open questions for future ablation studies. The architecture performs robustly on normal/primary lines (mean per-cell-line PCC = 0.480) but faces clear challenges on more heterogeneous cancer lines (0.296), indicating that scalability is cell-type dependent; the platform nevertheless serves as a candidate-screening and hypothesis-generation tool for novel drugs and cell lines."),
  h2("Data and Code Availability"),
  p("All training data are from public repositories: LINCS L1000 (GSE92742, level 5 moderated Z-scores), DepMap CRISPR (23Q2, CERES scores), ChEMBL (release 37), and GEO perturbation datasets (GSE61302, GSE11917, GSE17579, GSE20986, GSE21413, GSE25941, GSE33622, GSE50378, GSE50397, GSE53751, GSE62914, GSE22886, GSE60235). Preprocessed data matrices and trained model weights (g2cp_full_cpi_v7.pt) are available upon reasonable request. Source code is publicly available on GitHub: https://github.com/wkr112344/G2CP-virtual-cell. An interactive API and Web frontend are included in the repository."),
  h2("Declarations"),
  p("Competing interests: The authors declare no competing interests."),
  p("Funding: This work received no specific grant from any funding agency in the public, commercial, or not-for-profit sectors."),
  p("Ethics statement: This study used exclusively publicly available, anonymized datasets and involved no human or animal subjects; therefore, no ethical approval was required."),
  p("Author contributions: K.W. conceived the study, implemented the core architecture and training pipeline, conducted all computational experiments, and wrote the manuscript. L.Z. developed the interactive web interface and visualization components. C.Q. contributed to evaluation benchmarking and biological validation data curation. All authors reviewed and approved the manuscript."),
  h2("References"),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[1] Li Y, et al. Unified genetic and chemical perturbation prediction across cell lines with UniPert-G2CP. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Cell", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2026;189(13):2678-2695.e18. doi:10.1016/j.cell.2026.06.005.", size: 22, font: "Times New Roman" })] }),
  p("[2] lynn-1998. UniPert-G2CP_reproduce [Source code]. GitHub. 2026. https://github.com/lynn-1998/UniPert-G2CP_reproduce. Accessed August 7, 2026."),
  p("[3] Li Y, et al. UniPert-G2CP: evaluation data and model outputs [Data set]. Zenodo. 2026. doi:10.5281/zenodo.20355906."),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[4] Lin Z, et al. Evolutionary-scale prediction of atomic-level protein structure with a language model. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Science", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2023;379(6637):1123-1130. doi:10.1126/science.ade2574.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[5] Subramanian A, et al. A next generation connectivity map: L1000 platform and the first 1,000,000 profiles. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Cell", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2017;171(6):1437-1452.e17. doi:10.1016/j.cell.2017.10.049.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[6] Roohani Y, Huang K, Leskovec J. Predicting transcriptional outcomes of novel and known multi-gene perturbations with GEARS. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Nat Biotechnol", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2024;42(6):927-936. doi:10.1038/s41587-023-01905-6.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[7] Gao H, et al. Suppression of CD36 attenuates adipogenesis with a reduction of P2X7 expression in 3T3-L1 cells. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Biochem Biophys Res Commun", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2017;491(1):42-48. doi:10.1016/j.bbrc.2017.07.077.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[8] Ayroldi E, et al. GILZ mediates the antiproliferative activity of glucocorticoids by negative regulation of Ras signaling. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "J Clin Invest", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2007;117(6):1605-1615. doi:10.1172/JCI30724.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[9] Ueno S, et al. Metformin enhances anti-tumor effect of L-type amino acid transporter 1 (LAT1) inhibitor. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "J Pharmacol Sci", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2016;131(2):110-117. doi:10.1016/j.jphs.2016.04.021.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[10] Lotfollahi M, Wolf FA, Theis FJ. scGen predicts single-cell perturbation responses. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Nature Methods", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2019;16(8):715-721.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[11] Lotfollahi M, et al. Predicting cellular responses to complex perturbations in high-throughput screens. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Molecular Systems Biology", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2023;19(6):e11517.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[12] Hetzel L, Boehm V, Kilbertus N, Guennemann S, Lotfollahi M, Theis FJ. Predicting cellular perturbation responses for unseen drugs. arXiv:2204.13545 [q-bio.QM]. 2022.", size: 22, font: "Times New Roman" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[13] Obeng EA, Carlson LM, Gutman DM, Harrington WJ Jr, Lee KP, Boise LH. Proteasome inhibitors induce a terminal unfolded protein response in multiple myeloma cells. ", size: 22, font: "Times New Roman" }), new TextRun({ text: "Blood", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2006;107(12):4907-4916.", size: 22, font: "Times New Roman" })] }),
];

const enDoc = new Document({
  styles: { default: { document: { run: { font: "Times New Roman", size: 22 } } } },
  sections: [{ properties: { page: { size: { width: A4_W, height: A4_H }, margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN } } }, footers: { default: foot }, children: enChildren }]
});

// ==================== CHINESE ====================
const cnChildren = [
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 4 }, children: [new TextRun({ text: "重新实现与扩展 UniPert-G2CP：", bold: true, size: 32, font: "SimSun" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 4 }, children: [new TextRun({ text: "一个面向扰动-表型预测的 162 细胞系全基因组平台", bold: true, size: 28, font: "SimSun" })] }),
  pc(""),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "卫铠睿\u00B9*，詹丽静\u00B9，齐灿阳\u00B9", bold: true, size: 26, font: "SimSun" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: "\u00B9 新疆医科大学，乌鲁木齐 830011，中国", size: 22, font: "SimSun" })] }),
  pc(""),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "*通讯作者：2742391737@qq.com", size: 20, color: "666666", font: "SimSun" })] }),
  hr(CONTENT_W),
  h2("摘要"),
  p("UniPert-G2CP（Li 等，Cell，2026）提出了一个统一框架，用于在五种癌细胞系上预测遗传扰动和化学扰动的转录组响应。迄今为止，尚无人独立重新实现或大规模扩展该框架。"),
  p("我们构建了 UniPert-G2CP 架构的简化变体，集成了扩展连接指纹 4（ECFP4）化合物指纹、以静态 ESM2-8M 基因嵌入（替代原文 MSA+GNN 蛋白编码器）作为化合物-蛋白互作（CPI）对齐的锚点、NT-Xent 对比学习与两阶段迁移，并将其扩展到大幅扩增的化合物与细胞系覆盖（162 种细胞系上的 32,039 种化合物），输出全基因组（12,328 个基因）。"),
  p("留出集遗传扰动 PCC = 0.442；新药 PCC = 0.3047；效应量前 5% 基因的方向准确率 = 73.8%。CPI 富集因子（前 0.5%）在 Touchstone 集上达到 139，但该指标因与训练 CPI 对重叠而主要反映训练集内的排名一致性，而非跨分布泛化。基准一致评估：机制聚类标准化均数差（SMD）= 1.636；自一致性 Mantel \u03c1 = 0.852（本评估设定下）；Tanimoto SMD 验证 = 1.613。四个有文献支持的扰动-基因对查询中，有两个在模型输出中得到复现（地塞米松 \u2192 HA1E 中 TSC22D3/NFKBIA/FKBP5 上调；硼替佐米 \u2192 HA1E 中 BAG3/DNAJB1/HSPA1A 上调），一个未出现（ASC 中 CD36 缺失 \u2192 PPARG/CEBPA），一个部分复现（HEPG2 中二甲双胍的 SLC7A5 下调被预测，PLIN2 未出现）。"),
  p("该架构可扩展到更高的细胞系与化合物多样性，但在两个方面未达到原始研究的水平：机制聚类 SMD 低于原始研究数值（1.636 vs. 1.85；鉴于训练配置不同，此为参考性比较），可能部分与 CPI 词汇不匹配相关；以及部分源于通路覆盖不全和细胞类型分布偏移的逐基因方向预测保真度有限。所有结果均为计算假设，未经实验验证。这些发现为 UniPert-G2CP 在扩展规模下提供了首个独立基准，揭示了全基因组虚拟细胞预测的内在瓶颈。"),
  p(""),
  p("关键词：扰动预测、转录组学、对比学习、药物响应、CRISPR 筛选、转录组扰动"),
  hr(CONTENT_W),
  h2("1. 引言"),
  p("预测分子扰动后的转录组响应已成为 AI 驱动生物学中的核心挑战。已有多种方法被提出：scGen [10] 使用变分自编码器预测单细胞扰动响应；CPA [11] 使用自编码器框架进行组合扰动预测；ChemPert [12] 通过多任务模型预测药物诱导的转录组变化；GEARS [6] 引入了整合基因共表达关系的图框架。UniPert-G2CP（Li 等，Cell，2026）[1] 在五种癌细胞系上的统一对比嵌入空间中统一了遗传与化学扰动预测。迄今为止，尚无对 UniPert-G2CP 的独立重新实现或大规模扩展的报道。"),
  p("本研究受独立验证该架构可复现性与可扩展性的需求驱动。原始研究已公开代码与复现资源 [2,3]；我们未直接使用它们，而是根据论文描述重建该架构，以检验关键设计组件在更大规模下是否依然成立。"),
  p("本研究贡献：(1) 在显著扩展的化合物与细胞系覆盖（32,039 种化合物、162 种细胞系、全基因组输出）下独立全尺寸重建该架构；(2) 一个解耦的评估框架，区分留出预测、自一致性与基准一致指标；(3) 在文献支持案例上对逐基因预测保真度进行透明评估。本工作是 UniPert-G2CP 框架 [1] 的独立重新实现与扩展，与原作者无关联。与原始结果的所有比较均基于公开发布的评估数据集 [3]。"),
  h2("2. 方法"),
  h3("2.1 数据集与预处理"),
  p("我们使用了 LINCS L1000（level 5，GSE92742；moderated Z 分数，305,297 个样本）、DepMap CRISPR 筛选（23Q2 版本，CERES 基因效应分数，1,095 种细胞系 \u00d7 17,931 个基因）以及将 BRD 化合物 ID（LINCS 平台的化合物标识符）链接到治疗性作用机制（MoA）标签的扰动共识配体（PCL）注释。我们保留了 143 个具有 LINCS level-5 训练样本的细胞系作为训练域，并纳入来自 12 个 GEO（基因表达综合数据库，Gene Expression Omnibus）扰动数据集的 19 个 GEO 来源细胞系（HUVEC、PBMC 免疫亚群及其他原代/血管/胰腺细胞系；未纳入模型训练，仅用于域外评估）（GSE11917、GSE17579、GSE20986、GSE21413、GSE25941、GSE33622、GSE50378、GSE50397、GSE53751、GSE62914、GSE22886、GSE60235），构成 162 种细胞系的词表。ASC 是 LINCS 训练域细胞系（GSE61302 提供额外 GEO 数据）；第 3.5 节中 CD36 敲除 × ASC 查询因该系缺乏基因扰动训练样本而构成零样本预测。探针级表达在合并前映射为基因符号，并按样本进行 z-score 标准化（对齐 LINCS level-5 口径）。全化合物集包含 32,039 种具有 LINCS level-5 特征的 BRD 化合物；其 ECFP4 指纹（2048 位，半径 2）通过 RDKit Morgan 指纹生成。"),
  h3("2.2 模型架构"),
  p("架构遵循 UniPert-G2CP：药物编码器（ECFP4，2048 位 \u2192 512 维线性层）；基因编码器（4,994\u00d7512 嵌入表，前 320 维由 ESM2-8M 向量初始化，其余 192 维保持 Embedding 层默认随机初始化；该嵌入表在阶段 B 微调中保持冻结）；带 NT-Xent（\u03c4=0.07）与 CPI 对齐（第 2.3 节）的对比学习；表型头（LayerNorm(544)\u2192线性层(544\u21921024)\u2192GELU\u2192线性层(1024\u219212,328)，无丢弃层）；细胞嵌入（162\u00d732，可学习）。关键的是，基因嵌入表在阶段 B 微调中保持冻结；ESM2 向量作为 CPI 对齐的固定参考目标，而非可训练的蛋白质结构表征。4,994 个可扰动基因构成扰动词汇；12,328 基因输出为预测词汇（DepMap\u2013LINCS 交集的高变异基因）。"),
  h3("2.3 训练协议"),
  p("训练分两阶段进行。阶段 A（DepMap 预训练）：在 CERES 基因效应分数上预训练基因必需性网络（基因嵌入以 ESM2-8M 向量初始化），提供基因语义初始化。阶段 B（LINCS 微调）：在 LINCS level-5 moderated Z 分数上以冻结模式训练主模型——基因编码器、表型头与细胞嵌入保持冻结，仅微调药物编码器（ECFP4 投影）——该冻结设计使基因侧参数逐位不变，从而在化学微调期间保持遗传扰动预测指标——使用 AdamW（学习率 3\u00d710\u207B\u2074，权重衰减 1\u00d710\u207B\u2074，40 轮，余弦退火调度，梯度累积因子 4），经部分状态字典迁移由先前 LINCS 训练检查点初始化。总损失由表型回归损失（MSE 加 1\u2212PCC，权重 1.0）、NT-Xent 对比损失（\u03c4=0.07，权重 1.0；负对为批内随机样本）、CPI 对齐损失（权重 0.8；正对为共享至少一个 ChEMBL（第 37 版）治疗靶点的药物-基因对，共 19,161 对，每批动态采样至多 128 对；每个正对从基因词表中均匀随机采样 1 个负基因，未排除潜在靶点）、结构相似性增强损失（权重 0.3；对批内 Tanimoto 指纹相似度 >0.3 的药物对，按相似度加权拉近其嵌入）与 ESM 锚定损失（权重 0.05；基因嵌入前 320 维的 MSE 损失拉向预计算的 ESM2-8M 向量）组成。阶段 A 中 DepMap CERES 基因效应分数直接用作回归目标（缺失值掩码）；阶段 B 中以 LINCS moderated Z 分数为回归目标。两种模态在阶段 B 共享同一个表型头。细胞嵌入是一个可学习的 32 维表（初始化为 N(0,1)），在阶段 B 中保持冻结；阶段 A 训练独立的 DepMap 必需性网络（含其自身的 1,095 系细胞嵌入），该表并非阶段 B 使用的 162 系 LINCS 细胞嵌入。ESM2-8M 向量在预处理时计算一次（第 4.2 节），此后保持冻结。"),
  p("第 3.1\u20133.4 节报告的所有量化指标均来自按上述配置训练的单一模型（g2cp_full_cpi_v7.pt）；评估后未进行任何事后超参数调整。第 3.5 节的案例查询通过交互式 API 平台完成。"),
  h2("3. 结果"),
  h3("3.1 留出扰动预测"),
  p("指标。PCC：预测与实测表达变化之间的皮尔逊相关系数，按留出样本对所有基因计算后取平均。方向准确率：预测变化符号与实测变化符号一致的基因比例；前 5% 按基因的绝对实测效应量排序。SMD：标准化均数差，计算为（类内余弦相似度均值 \u2212 总体余弦相似度均值）/ 合并标准差，按作用机制对药物分组。Mantel 自一致性 \u03c1：逐 PCL 计算分子嵌入相似性与模型预测效应相似性之间的 Spearman 相关，跨细胞系平均（评估脚本见仓库）。"),
  pb("表 1. 留出扰动预测性能。扰动（药物或基因身份）随机划分，10% 分配给测试集；被留出扰动的所有样本（各剂量与细胞系）均排除在训练之外。遗传扰动 PCC：扰动级留出评估（留出 10% 的扰动），在 162 种细胞系上对遗传扰动样本、具有 DepMap CERES 真值的 978 基因子集计算（即 LINCS L1000 平台测量探针覆盖的 978 个 landmark 基因；敲除样本仅这些基因有实测值）。新药 PCC：扰动级留出评估（留出 10% 的扰动），对化学扰动样本在全 12,328 基因输出上计算。方向准确率：留出集中效应量前 5% 的基因。"),
  tbl(["指标","数值","说明"],
    [["遗传扰动 PCC","0.442","留出 10% 扰动"],["新药 PCC","0.3047","原文未报告"],["方向准确率（全基因组）","60.8%","随机基线 50%"],["方向准确率（前 5%）","73.8%","随机基线 50%"]]),
  h3("3.2 化合物-蛋白互作富集"),
  pb("表 2. 各百分位 CPI 富集因子（随机基线 = 1）。该指标反映训练注释空间内的排名一致性，而非跨分布泛化（见 4.1 节）。"),
  tbl(["百分位","本研究"],
    [["前 0.5%","139"],["前 1%","77"]]),
  h3("3.3 基准一致评估"),
  pb("表 3. 原始评估数据集上的基准一致指标。评估集说明澄清了数据范围差异。"),
  tbl(["指标","本研究"],
    [["SMD（余弦）","1.636"],["ECFP4 Tanimoto SMD","1.613"],["Mantel 自一致性 \u03c1","0.852"],["细胞系","162"]]),
  p("注：SMD 使用原始研究 Zenodo 数据集 [3] 发布的 MoA 评测表（ChEMBL 治疗药物）计算，类过滤标准（每类>25 药物）与原始研究一致，由于训练配置（CPI 对、蛋白编码器）与原研究不同，SMD 数值作为参考性比较呈现（1.636 vs. 1.85），而非严格的复现差距。Mantel \u03c1 使用 Subramanian PCL [5] 机制注释、按原始研究定义复刻的脚本计算；由于 PCL 过滤与细胞系选择与原始研究不同，Mantel \u03c1 数值不可直接比较（0.852 vs. 0.43，仅作参考）。"),
  h3("3.4 逐细胞系药物扰动分辨率"),
  p("我们在训练域内评估单细胞系分辨率，对每种细胞系（120 个样本充足的细胞系）分别计算留出药物扰动 PCC。逐细胞系 PCC 均值为 0.359（中位 0.362，范围 \u22120.004 至 0.615；A549 = 0.362，MCF7 = 0.360）。按细胞类型分层：癌细胞系（n = 78）PCC 均值较低（0.296，中位 0.324），正常/原代细胞系（n = 37）为 0.480（中位 0.502），干/神经/脂肪细胞系（n = 5）为 0.446——表明异质性更强的癌细胞系预测难度更高。该指标在扰动级留出划分（训练中未见药物）下于全基因集（12,328 基因）上计算。原始研究在 sciPlex3 上报告 PCC = 0.92\u20130.98 [1]，但那些数值是在近域划分（已知化合物、新剂量/新细胞系）下、于 top-DEG 子集上计算得到的；我们更低的逐细胞系数值反映了在更大、更多样的 LINCS 筛选库上进行全基因、未见扰动评估的更严格设置。"),
  h3("3.5 文献支持对的计算机内案例查询"),
  p("所有预测均为计算假设，未经实验验证。这些案例仅用于说明模型行为，不构成疗效证据。四个案例仅依据文献可获得性选取，未用于调整任何模型超参数。它们选自特征明确、经过实验验证的扰动-基因对，覆盖脂肪生成、糖皮质激素、蛋白毒性应激与代谢通路；选择标准是文献支持而非正向模型表现。涉及三种细胞系：HA1E（两个案例）与 HEPG2 在核心训练集中；ASC 亦在训练域词表内，但缺乏基因扰动训练样本，因此 CD36 敲除 \u2192 ASC 构成零样本预测场景。为评估模型是否重现已知的扰动-基因关系，我们以匹配的扰动-细胞系组合查询了四个有文献支持的对（表 4）。其中两对在模型输出中得到复现。地塞米松处理 HA1E 细胞上调 TSC22D3（GILZ）、NFKBIA（I\u03baB\u03b1）、FKBP5 与 CEBPD——糖皮质激素受体的经典直接靶基因 [8]。硼替佐米（蛋白酶体抑制剂）处理 HA1E 细胞上调 BAG3、DNAJB1 与 HSPA1A——蛋白酶体抑制诱导热休克响应基因是公认机制 [13]。然而，一对——ASC 中 CD36 缺失 \u2192 PPARG/CEBPA 下调——未出现在预测的差异表达基因中。ASC 中预测的 HLA-A/HLA-C 上调而非预期的脂肪生成标志物，可能反映 LINCS 训练数据中该细胞系的批次效应或细胞状态相关信号，凸显了将扰动特异性效应与实验混杂因素分离的挑战。对于 HEPG2 中的二甲双胍，模型预测了 SLC7A5 下调（下调基因中排名第 6，与文献方向一致 [9]），而 PLIN2 未出现。当缺失时，表 4 报告模型的实际 top 预测。我们通过计算评估了特异性：确认标记基因（TSC22D3、FKBP5、BAG3、DNAJB1、HSPA1A）不在同一 HA1E 细胞系中其他七种药物（伏立诺他、他莫昔芬、二甲双胍、顺铂、伊马替尼、厄洛替尼、索拉非尼）的前 10 个预测上调基因之列；BAG3 出现在厄洛替尼的前 10 个下调基因中（第 8 位），方向与硼替佐米相反。"),
  pb("表 4. 文献支持对的计算机内案例查询结果。展示原始预测；复现案例已通过药物特异性验证（标记基因不被同一细胞系中其他药物预测）。"),
  tbl(["扰动","预测基因","模型匹配"],
    [["CD36 扰动 × ASC","模型：HLA-A↑, HLA-C↑, GAPDH↑, RAC2↑ 文献：PPARG↓, CEBPA↓ [7]","未复现；模型预测其他基因"],["地塞米松 × HA1E","TSC22D3↑, NFKBIA↑, FKBP5↑, CEBPD↑","模型复现 [8]"],["硼替佐米 × HA1E","BAG3↑, DNAJB1↑, HSPA1A↑, HMOX1↑","模型复现 [13]"],["二甲双胍 × HEPG2","模型：SLC7A5↓（第6），UBC↑（第9） 文献：SLC7A5↓, PLIN2↓ [9]","部分复现：SLC7A5↓ 被预测；PLIN2 未出现"]]),
  p("总体而言，四个案例中两个完全复现、一个未出现、一个部分恢复。这些结果代表四个案例的初步集合，不应被解读为系统性评估。在概括逐基因方向预测保真度之前，需要更大规模的验证。缺失的文献支持关系（CD36 \u2192 PPARG/CEBPA）与部分恢复的二甲双胍案例（SLC7A5↓ 被预测、PLIN2 未出现）凸显了全基因组准确率（PCC = 0.442）与逐基因可靠性（60.8% 方向准确率）之间的差距，并反映了 LINCS 训练数据中通路表征有限以及留出系上的细胞类型分布偏移。"),
  h2("4. 讨论"),
  h3("4.1 贡献"),
  p("本研究有三项贡献。第一，它在显著扩展的化合物与细胞系覆盖（跨 162 种细胞系的 32,039 种化合物、全基因组输出）下独立构建了 UniPert-G2CP 架构，证明该架构可复现且可扩展到原始五系设置之外。第二，它厘清了原始评估框架中留出泛化指标与自一致性指标的边界，明确了每类指标的解读前提。第三，它提供了跨多条通路的文献支持定性案例展示，透明报告阳性与阴性结果。"),
  p("留出扰动指标（遗传扰动 PCC = 0.442；新药 PCC = 0.3047；前 5% 效应基因方向准确率 = 73.8%）作为独立参考值报告。CPI 富集（EF = 139，前 0.5%）在 Touchstone CPI 评估集（LINCS 机制注释的化合物-靶点验证集；797 种化合物 \u00d7 225 个靶基因；近似评估，非严格留出）上计算；剔除与训练 CPI 对重叠的评测对（占正样本的 54.9%）后，EF 仍为 109，该指标主要反映训练注释空间内的排名一致性，而非跨分布泛化能力；此处仅作参考。自一致性 Mantel \u03c1（0.852）在 Subramanian PCL [5] 机制注释上计算（过滤为每类 \u22653 药物：48 类、366 种化合物）。在不同 PCL 集上获得的值不应直接比较。所有指标均应在各自评估背景下解读。"),
  h3("4.2 静态蛋白嵌入锚定的原理"),
  p("对于 4,994 个可扰动基因中的每一个，蛋白序列取自 UniProt 人源已审校（Swiss-Prot）蛋白组（reviewed:true，organism:9606），通过 FASTA 头部的基因符号（GN= 字段）匹配；12 个未匹配到蛋白序列的基因赋予零向量。ESM2-8M [4] 编码在预处理时于 NVIDIA RTX 3050 Ti GPU（4 GB 显存）上执行一次：顶层逐残基表征经均值池化得到 320 维向量，锚定 512 维基因嵌入表的前 320 维。基因嵌入表在阶段 B 微调及后续训练中保持冻结。我们的简化设计刻意通过静态蛋白先验隔离 CPI 对齐对化合物嵌入空间的影响，但后果是蛋白质结构信息未整合进预测通路。相对原始可训练蛋白 GNN，这是一项关键简化，可能促成观察到的 SMD 差距。纳入 MSA 与可训练 GNN 编码是未来工作方向。"),
  h3("4.3 SMD 差距分析"),
  p("由于 SMD 使用与原研究相同的 MoA 评测表和相同的类过滤标准（每类>25 药物）计算（表 3 注），该比较可直接解读：机制聚类 SMD 在学习到的嵌入上为 1.636，超过 ECFP4 Tanimoto 指纹基线（1.613），但仍低于原始研究的 1.85（达成率 88.5%）。我们对剩余差距假设两个因素：(1) CPI 词汇不匹配：此处使用的 CPI 训练对基于 LINCS BRD 化合物词汇的 ChEMBL 注释（19,161 个唯一对）；它们与原始研究所用化合物-靶点对差异显著，可能基于噪声靶点注释将一些结构不同的化合物映射到相似向量。(2) 目标冲突：最小化转录 MSE 可能将效应不同的化合物在嵌入空间中分开，即使它们共享同一机制。替代解释（蛋白编码器简化、冻结基因编码器限制对比学习、超参数敏感性、数据分布差异）仍然合理，应在未来消融研究中系统检验。"),
  h3("4.4 局限"),
  p("(1) 单基因方向预测仍显嘈杂（全基因组 60.8%）；该平台是候选筛选与假设生成工具，而非实验验证的替代品。(2) 蛋白编码器相对原始版本有所简化。(3) 在当前化合物词汇下，CPI 训练数据已达物理上限。(4) SMD 评估数据集反映特征明确的治疗药物属性，不代表筛选文库化合物。(5) 原始研究已公开代码与预训练模型 [2,3]；我们的独立实现基于论文描述构建，未直接使用其发布的训练管线，因此可能存在实现差异。(6) 细胞系覆盖增加引入更大的生物学异质性，其本身可能降低聚合性能指标；全基因组输出（12,328 基因）比原始标志基因预测更具挑战性。基因嵌入表中随机初始化并冻结的 192 维可能影响基因表征质量；这些维度继承自早期 512 维架构并为保持检查点兼容而保留，我们未对该设计进行消融。未来工作可探索全维 ESM2 初始化或可训练基因嵌入。未来工作包括：通过消融研究隔离各架构组件的贡献；纳入原始 MSA 与蛋白相似性 GNN 管线；扩展到单细胞分辨率；以及构建与化合物词汇匹配的领域特异 CPI 注释数据集。"),
  h2("5. 结论"),
  p("我们已在增加的细胞系与化合物多样性（162 种细胞系、32,039 种化合物、全基因组输出）下独立构建并评估了 UniPert-G2CP 架构。该架构复现了原始设计的关键特性，但机制聚类 SMD 低于原始研究数值（1.636 vs. 1.85）且逐基因方向预测保真度有限——其根本原因（CPI 词汇不匹配 vs. 目标冲突 vs. 超参数调优）仍是未来消融研究的开放问题。该架构在正常/原代细胞系中表现稳健（逐细胞系 PCC 均值 0.480），但在异质性更高的肿瘤细胞系中面临明显挑战（0.296），表明可扩展性存在细胞类型依赖；该平台仍可作为针对新药与新细胞系的候选筛选与假设生成工具。"),
  h2("数据与代码可用性"),
  p("所有训练数据均来自公共仓库：LINCS L1000（GSE92742，level 5 moderated Z 分数）、DepMap CRISPR（23Q2，CERES 分数）、ChEMBL（第 37 版）以及 GEO 扰动数据集（GSE61302、GSE11917、GSE17579、GSE20986、GSE21413、GSE25941、GSE33622、GSE50378、GSE50397、GSE53751、GSE62914、GSE22886、GSE60235）。预处理数据矩阵与训练模型权重（g2cp_full_cpi_v7.pt）可应合理请求提供。源代码在 GitHub 上公开：https://github.com/wkr112344/G2CP-virtual-cell。仓库中包含交互式 API 与 Web 前端。"),
  h2("声明"),
  p("利益冲突：作者声明不存在利益冲突。"),
  p("基金：本工作未获得公共、商业或非营利部门任何资助机构的具体资助。"),
  p("伦理声明：本研究仅使用公开可用的匿名数据集，不涉及人类或动物受试者；因此无需伦理审批。"),
  p("作者贡献：K.W. 构思研究，实现核心架构与训练管线，开展全部计算实验并撰写手稿。L.Z. 开发交互式 Web 界面与可视化组件。C.Q. 参与评估基准与生物学验证数据整理。所有作者审阅并批准手稿。"),
  h2("参考文献"),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[1] Li Y 等. Unified genetic and chemical perturbation prediction across cell lines with UniPert-G2CP. ", size: 22, font: "SimSun" }), new TextRun({ text: "Cell", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2026;189(13):2678-2695.e18. doi:10.1016/j.cell.2026.06.005.", size: 22, font: "SimSun" })] }),
  p("[2] lynn-1998. UniPert-G2CP_reproduce [源代码]. GitHub. 2026. https://github.com/lynn-1998/UniPert-G2CP_reproduce. 访问日期 2026年8月7日."),
  p("[3] Li Y 等. UniPert-G2CP: evaluation data and model outputs [数据集]. Zenodo. 2026. doi:10.5281/zenodo.20355906."),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[4] Lin Z 等. Evolutionary-scale prediction of atomic-level protein structure with a language model. ", size: 22, font: "SimSun" }), new TextRun({ text: "Science", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2023;379(6637):1123-1130. doi:10.1126/science.ade2574.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[5] Subramanian A 等. A next generation connectivity map: L1000 platform and the first 1,000,000 profiles. ", size: 22, font: "SimSun" }), new TextRun({ text: "Cell", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2017;171(6):1437-1452.e17. doi:10.1016/j.cell.2017.10.049.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[6] Roohani Y, Huang K, Leskovec J. Predicting transcriptional outcomes of novel and known multi-gene perturbations with GEARS. ", size: 22, font: "SimSun" }), new TextRun({ text: "Nat Biotechnol", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2024;42(6):927-936. doi:10.1038/s41587-023-01905-6.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[7] Gao H 等. Suppression of CD36 attenuates adipogenesis with a reduction of P2X7 expression in 3T3-L1 cells. ", size: 22, font: "SimSun" }), new TextRun({ text: "Biochem Biophys Res Commun", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2017;491(1):42-48. doi:10.1016/j.bbrc.2017.07.077.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[8] Ayroldi E 等. GILZ mediates the antiproliferative activity of glucocorticoids by negative regulation of Ras signaling. ", size: 22, font: "SimSun" }), new TextRun({ text: "J Clin Invest", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2007;117(6):1605-1615. doi:10.1172/JCI30724.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[9] Ueno S 等. Metformin enhances anti-tumor effect of L-type amino acid transporter 1 (LAT1) inhibitor. ", size: 22, font: "SimSun" }), new TextRun({ text: "J Pharmacol Sci", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2016;131(2):110-117. doi:10.1016/j.jphs.2016.04.021.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[10] Lotfollahi M, Wolf FA, Theis FJ. scGen predicts single-cell perturbation responses. ", size: 22, font: "SimSun" }), new TextRun({ text: "Nature Methods", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2019;16(8):715-721.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[11] Lotfollahi M 等. Predicting cellular responses to complex perturbations in high-throughput screens. ", size: 22, font: "SimSun" }), new TextRun({ text: "Molecular Systems Biology", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2023;19(6):e11517.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[12] Hetzel L, Boehm V, Kilbertus N, Guennemann S, Lotfollahi M, Theis FJ. Predicting cellular perturbation responses for unseen drugs. arXiv:2204.13545 [q-bio.QM]. 2022.", size: 22, font: "SimSun" })] }),
  new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: "[13] Obeng EA 等. Proteasome inhibitors induce a terminal unfolded protein response in multiple myeloma cells. ", size: 22, font: "SimSun" }), new TextRun({ text: "Blood", italics: true, size: 22, font: "Times New Roman" }), new TextRun({ text: ". 2006;107(12):4907-4916.", size: 22, font: "SimSun" })] }),
];

const cnDoc = new Document({
  styles: { default: { document: { run: { font: "SimSun", size: 22 } } } },
  sections: [{ properties: { page: { size: { width: A4_W, height: A4_H }, margin: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN } } }, footers: { default: foot }, children: cnChildren }]
});

async function main() {
  const enBuf = await Packer.toBuffer(enDoc);
  fs.writeFileSync("biorxiv_english.docx", enBuf);
  console.log("EN Word: biorxiv_english.docx", (enBuf.length/1024).toFixed(0) + "KB");

  const cnBuf = await Packer.toBuffer(cnDoc);
  fs.writeFileSync("biorxiv_chinese.docx", cnBuf);
  console.log("CN Word: biorxiv_chinese.docx", (cnBuf.length/1024).toFixed(0) + "KB");
}
main().catch(e => { console.error(e); process.exit(1); });
